sync_topics: ['/dragonfly2/attach',
  '/dragonfly2/odom',
  '/dragonfly3/attach',
  '/dragonfly3/odom',
  '/dragonfly6/attach',
  '/dragonfly6/odom',
  '/payload/cen_pl_cmd',
  '/payload/payload_copr_status',
  #'/dragonfly2/so3_control/rbpl_so3_cmd',
  #'/dragonfly3/so3_control/rbpl_so3_cmd',
  #'/dragonfly6/so3_control/rbpl_so3_cmd'
  ]
ignore_nodes: ['']
ignore_services: ['']
