sync_topics: ['/dragonfly_2/attach',
  '/dragonfly_2/odom',
  '/dragonfly_3/attach',
  '/dragonfly_3/odom',
  '/dragonfly_6/attach',
  '/dragonfly_6/odom',
  '/payload/cen_pl_cmd'
  ]
ignore_nodes: ['']
ignore_services: ['']
