sync_topics: ['/dragonfly2/attach',
  '/dragonfly2/odom',
  '/dragonfly2/q_vec',
  '/payload/cen_pl_cmd',
  '/dragonfly2/whycon/whycon_emergency',
  #'/dragonfly2/so3_cmd',
  #'/dragonfly2/so3_control/rbpl_so3_cmd',
  '/payload/payload_copr_status'
  ]
ignore_nodes: ['']
ignore_services: ['']
