sync_topics: ['/dragonfly6/attach',
  '/dragonfly6/odom',
  '/dragonfly6/attach_info',
  #'/dragonfly6/q_vec',
  #'/dragonfly6/quadrotor_ukf/control_odom',
  '/dragonfly6/whycon/whycon_emergency',
 # '/dragonfly6/so3_cmd',
 # '/dragonfly6/so3_control/rbpl_so3_cmd',
  '/payload/cen_pl_cmd',
  '/payload/payload_copr_status'
  ]
ignore_nodes: ['']
ignore_services: ['']
