sync_topics: ['/dragonfly3/attach',
  '/dragonfly3/odom',
  '/dragonfly3/whycon/whycon_emergency',
  #'/dragonfly3/so3_control/rbpl_so3_cmd',
  '/payload/cen_pl_cmd',
  '/payload/payload_copr_status'
  ]
ignore_nodes: ['']
ignore_services: ['']
sync_services: ['']
